#!/bin/bash
processedName=Processed${1}

SECTION_START="layout: true\nsection: \1\n##{{ section }}\n---\n"

sed -r "s/\+\+(-+)/\n\1\n/; s/\+\+/\n/; s/^##\s+(.*)$/${SECTION_START}/" <$1 >$processedName

args=`echo $@ | sed s/$1/$processedName/`
base=`basename $1 .md`
base=`basename $base .markdown`
markdown-to-slides $args -o $base.html
rm $processedName

