#! /bin/bash

echo $1
if [[ $1 =~ (^.*)\.tex$ ]] ; then 
    echo matched
    pdflatex -halt-on-error $1 && rm "${BASH_REMATCH[1]}.log" && rm "${BASH_REMATCH[1]}.aux" 
else
    echo "$1 is not a .tex file."
fi
